import type { Metadata } from 'next'
export const metadata = {
    title: 'blog list',
    description: 'Generated by create next app',
}
export default function MetaLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>

    )
}
