
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'View Detail Blog',
  description: 'Generated by create next app',
}

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <>
        {children}
        </>
  )
}
